# Generated by Django 3.2.9 on 2021-11-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024)),
                ('middle_name', models.CharField(max_length=1024, null=True)),
                ('last_name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('company_name', models.CharField(max_length=1024)),
                ('address', models.TextField(max_length=1024)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=1024)),
                ('domain', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
        ),
    ]
