# Generated by Django 3.2.8 on 2021-11-02 09:21

from django.db import migrations, models
import django.db.models.deletion
import quality.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inspection_report_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('joborder_fin_material_bill_inward', models.PositiveIntegerField(null=True)),
                ('joborder_fin_material_dc_inward', models.PositiveIntegerField(null=True)),
                ('report_no', models.CharField(default=quality.models.reportnumber, max_length=1024, null=True)),
                ('inspection_date_start', models.DateTimeField(blank=True, null=True)),
                ('inspection_date_end', models.DateTimeField(blank=True, null=True)),
                ('sample_size', models.FloatField(null=True)),
                ('accepted_no', models.FloatField(null=True)),
                ('accepted_with_deviation_no', models.FloatField(null=True)),
                ('rejection_no', models.FloatField(null=True)),
                ('test_report', models.BooleanField(default=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('statusreport', models.CharField(blank=True, choices=[(1, 'OK'), (2, 'REJECTED')], max_length=100, null=True)),
                ('financial_year', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.FloatField(null=True)),
                ('field2', models.FloatField(null=True)),
                ('field3', models.FloatField(null=True)),
                ('field4', models.FloatField(null=True)),
                ('field5', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('remarks', models.CharField(choices=[(1, 'list1'), (2, 'list2'), (3, 'list3'), (4, 'list4'), (5, 'list5')], default=1, max_length=50)),
                ('inspection_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quality.inspection_report_details')),
            ],
        ),
        migrations.CreateModel(
            name='inspection_report_rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('no_of_sample', models.IntegerField(null=True)),
                ('smp_no', models.IntegerField(null=True)),
                ('parameter_required', models.CharField(max_length=30, null=True)),
                ('val', models.FloatField(null=True)),
                ('statusreport', models.CharField(blank=True, choices=[(1, 'ok'), (2, 'not ok'), (3, 'tested partially')], max_length=100, null=True)),
                ('inspection_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quality.inspection_report_details')),
            ],
        ),
    ]
