# Generated by Django 3.2.8 on 2021-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_inspection_report_details_data'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='inspection_report_details',
        #     name='data',
        # ),
        # migrations.AddField(
        #     model_name='inspection_report_details',
        #     name='worker_name',
        #     field=models.CharField(default=1, max_length=1024),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='inspection_report_rows',
        #     name='worker_name',
        #     field=models.CharField(default='raghav', max_length=1024),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='parameters',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='worker_name',
            field=models.CharField(default='Raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remarks',
            name='worker_name',
            field=models.CharField(default="raghav", max_length=1024),
            preserve_default=False,
        ),
    ]
