# Generated by Django 3.2.8 on 2021-11-02 09:30

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20211102_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_report_details',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
