# Generated by Django 3.2.8 on 2021-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_remove_inspection_report_details_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection_report_details',
            name='data',
        ),
        migrations.RemoveField(
            model_name='inspection_report_details',
            name='joborder_fin_material_bill_inward',
        ),
        migrations.RemoveField(
            model_name='inspection_report_details',
            name='joborder_fin_material_dc_inward',
        ),
        migrations.AddField(
            model_name='inspection_report_details',
            name='worker_name',
            field=models.CharField(default='raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection_report_rows',
            name='worker_name',
            field=models.CharField(default='raghav', max_length=1024),
            preserve_default=False,
        ),
    ]
