# Generated by Django 3.2.8 on 2021-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20211102_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_report_details',
            name='joborder_fin_material_bill_inward',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_details',
            name='joborder_fin_material_dc_inward',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
