# Generated by Django 3.2.8 on 2021-11-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20211102_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection_report_details',
            name='financial_year',
        ),
    ]
