# Generated by Django 3.2.8 on 2021-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_auto_20211102_1512'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='inspection_report_details',
        #     name='financial_year',
        # ),
        migrations.AddField(
            model_name='inspection_report_details',
            name='dde',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
