# Generated by Django 3.2.8 on 2021-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_auto_20211102_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection_report_details',
            name='dde',
        ),
        migrations.AddField(
            model_name='inspection_report_details',
            name='financial_year',
            field=models.DateField(auto_now=True),
        ),
    ]
