# Generated by Django 3.2.8 on 2021-11-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_auto_20211102_1515'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='inspection_report_rows',
        #     name='financial_year',
        # ),
    ]
