# Generated by Django 3.2.8 on 2021-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_remove_inspection_report_rows_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_report_rows',
            name='financial_year',
            field=models.DateField(auto_now=True),
        ),
    ]
