# Generated by Django 3.2.8 on 2021-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_inspection_report_rows_financial_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inspection_report_details',
            new_name='inspection_report_details_job_order',
        ),
        migrations.RenameModel(
            old_name='inspection_report_rows',
            new_name='inspection_report_rows_job_order',
        ),
    ]
