# Generated by Django 3.2.8 on 2021-10-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0002_auto_20211029_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_component_fin_material_dc_inward',
            old_name='job_order_price',
            new_name='raw_component_price',
        ),
    ]
