# Generated by Django 3.2.8 on 2021-10-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0003_rename_job_order_price_raw_component_fin_material_dc_inward_raw_component_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_component_fin_bill_inward_details',
            name='worker_name',
            field=models.CharField(default='Raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_component_fin_dc_inward_details',
            name='worker_name',
            field=models.CharField(default='raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_component_fin_material_bill_inward',
            name='worker_name',
            field=models.CharField(default='Raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_component_fin_material_dc_inward',
            name='worker_name',
            field=models.CharField(default='raghav', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_no_generation',
            name='worker_name',
            field=models.CharField(default='raaghav', max_length=1024),
            preserve_default=False,
        ),
    ]
