# Generated by Django 3.2.8 on 2021-11-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_History',
            new_name='Stock_History_job_order',
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stock_job_order',
        ),
    ]
