# Generated by Django 3.2.9 on 2021-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process_details',
            options={'verbose_name_plural': 'processdetails'},
        ),
        migrations.AlterField(
            model_name='process_bom',
            name='job_order_reqd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='process_bom',
            name='raw_material_reqd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='process_bom',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
