# Generated by Django 3.2.9 on 2021-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20211103_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_bom',
            name='job_order_reqd',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process_bom',
            name='raw_material_reqd',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
