# Generated by Django 3.2.9 on 2021-11-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20211103_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_bom',
            old_name='job_order_reqd',
            new_name='job_order',
        ),
        migrations.RenameField(
            model_name='process_bom',
            old_name='raw_material_reqd',
            new_name='raw_material',
        ),
    ]
