# Generated by Django 3.2.9 on 2021-11-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20211103_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_bom',
            name='job_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process_bom',
            name='raw_material',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
