# Generated by Django 3.2.8 on 2021-10-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder_fin_bill_inward_details',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder_fin_dc_inward_details',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder_fin_material_bill_inward',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder_fin_material_dc_inward',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_no_generation',
            name='tenant_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
