# Generated by Django 3.2.8 on 2021-11-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20211103_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='name',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
